[package]
name = "dragonfish"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { version = "0.8.20", features = ["nightly"] }
leptos_router = { version = "0.8.15", features = ["nightly"] }
axum = { version = "0.8.9", optional = true, features = ["macros", "tokio"] }
axum-macros = { version = "0.5.1", optional = true }
tower-cookies = { version = "0.11.0", features = ["private"], optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
leptos_axum = { version = "0.8.10", optional = true }
leptos_meta = { version = "0.8.6" }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"], optional = true }
wasm-bindgen = { version = "=0.2.127", optional = true }
dotenvy = { version = "0.15.7", optional = true }
cfg-if = { version = "1.0.4" }
strum = { version = "0.28.0", features = ["derive"] }
anyhow = { version = "1.0.104" }
thiserror = { version = "2.0.20" }
codee = { version = "0.3.5" }
lazyrand = { version = "0.1.13" }
slug = { version = "0.1.6" }
uuid = { version = "1.25.0", features = ["v4", "serde", "js"] }
email_address = { version = "0.2.9", optional = true }
sqlx = { version = "0.9.0", optional = true, default-features = false, features = ["runtime-tokio", "tls-native-tls", "postgres", "macros", "uuid", "chrono", "json", "derive"] }
apalis = { version = "1.0.0-rc.9", features = ["prometheus", "retry", "timeout", "limit", "filter", "catch-panic"], optional = true }
apalis-redis = { version = "1.0.0-rc.8", optional = true }
resend-rs = { version = "0.32.1", optional = true }
serde = { version = "1.0.229", features = ["derive"] }
chrono = { version = "0.4.45", features = ["serde", "wasmbind", "js-sys"] }
argon2 = { version = "0.6.0", optional = true }
ammonia = { version = "4.1.4", optional = true }
leptos-use = { version = "0.19.2" }
leptos_icons = { version = "0.7.1" }
icondata = { version = "0.7.0", default-features = false, features = ["tabler-icons"] }
comrak = { version = "0.54.0", default-features = false, features = ["cli", "syntect-fancy", "bon"] }

[features]
hydrate = [
    "leptos/hydrate",
    "dep:console_error_panic_hook",
    "dep:wasm-bindgen",
]
ssr = [
    "dep:axum",
    "dep:axum-macros",
    "dep:tower-cookies",
    "dep:tokio",
    "dep:leptos_axum",
    "dep:dotenvy",
    "dep:sqlx",
    "dep:apalis",
    "dep:apalis-redis",
    "dep:resend-rs",
    "dep:argon2",
    "dep:ammonia",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "leptos-use/ssr",
    "leptos-use/axum"
]

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.leptos]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
output-name = "dragonfish"

# The site root folder is where cargo-leptos generate all output. WARNING: all content of this folder will be erased on a rebuild. Use it in your server setup.
site-root = "target/site"

# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
# Defaults to pkg
site-pkg-dir = "pkg"

# [Optional] The source CSS file. If it ends with .sass or .scss then it will be compiled by dart-sass into CSS. The CSS is optimized by Lightning CSS before being written to <site-root>/<site-pkg>/dragonfish.css
# style-file = "style/main.scss"

# Assets source dir. All files found here will be copied and synchronized to site-root.
# The assets-dir cannot have a sub directory with the same name/path as site-pkg-dir.
#
# Optional. Env: LEPTOS_ASSETS_DIR.
assets-dir = "public"

# The IP and port (ex: 127.0.0.1:3000) where the server serves the content. Use it in your server setup.
site-addr = "127.0.0.1:3000"

# The port to use for automatic reload monitoring
reload-port = 3001

# [Optional] Command to use when running end2end tests. It will run in the end2end dir.
#   [Windows] for non-WSL use "npx.cmd playwright test"
#   This binary name can be checked in Powershell with Get-Command npx
end2end-cmd = "npx playwright test"
end2end-dir = "end2end"

#  The browserlist query used for optimizing the CSS.
browserquery = "defaults"

# The environment Leptos will run in, usually either "DEV" or "PROD"
env = "DEV"

# The features to use when compiling the bin target
#
# Optional. Can be over-ridden with the command line parameter --bin-features
bin-features = ["ssr"]

# If the --no-default-features flag should be used when compiling the bin target
#
# Optional. Defaults to false.
bin-default-features = false

# The features to use when compiling the lib target
#
# Optional. Can be over-ridden with the command line parameter --lib-features
lib-features = ["hydrate"]

# If the --no-default-features flag should be used when compiling the lib target
#
# Optional. Defaults to false.
lib-default-features = false

# The profile to use for the lib target when compiling for release
#
# Optional. Defaults to "release".
lib-profile-release = "wasm-release"

# The tailwind input file.
#
# Optional, Activates the tailwind build
tailwind-input-file = "style/styles.css"
