module.exports = {
    projects: [
        '<rootDir>/apps/bettafish',
        '<rootDir>/apps/api',
        '<rootDir>/libs/shared',
        '<rootDir>/libs/client/pipes',
        '<rootDir>/libs/client/ui',
        '<rootDir>/libs/client/alerts',
        '<rootDir>/libs/client/material',
        '<rootDir>/libs/client/icons',
        '<rootDir>/apps/bettafish-native',
        '<rootDir>/libs/client/editor',
        '<rootDir>/libs/client/dashboard',
        '<rootDir>/libs/client/services',
        '<rootDir>/libs/client/repository',
        '<rootDir>/libs/api/database',
        '<rootDir>/libs/api/utilities',
        '<rootDir>/libs/client/editor-lite',
        '<rootDir>/libs/client/my-library',
        '<rootDir>/libs/api/mail',
        '<rootDir>/libs/client/settings',
        '<rootDir>/libs/client/profile',
        '<rootDir>/libs/client/work-page',
    ],
};
