export const slogans: string[] = [
    "For the stories waiting to be told",
    "Tastes Like Fine Wine",
    "aaaaaaaaaaaaaaaaa",
    "Thanks for the cookies!",
    "Sample Text",
    "Not Secretly a Subsidiary of the Canadian Government",
    "Not Batman. Seriously.",
    "This is the dev team. We’re locked in a basement. Send help.",
    "Writer? I hardly even know ‘er!",
    "For All Your Times New Roman-Free Fanfiction Needs",
    "All-Natural, Ethically Sourced, Free Range, and Asbestos-Free",
    "You Probably Learned About This Site From Discord",
    "The archive we didn’t ask for, but the one we deserved",
    "Originally part of a larger publication",
    "We may or may not be Futurama fans",
    "",
    "Acquitted by a Jury of Our Peers",
    `Crime-free since ${new Date().toLocaleString()}`,
    "May contain nuts",
    "On-Brand",
    `Don't think about it too hard`,
    "Find the Comic Sans and Win a Prize",
    "There is no dress code",
    "Our slogan changes every 5 seconds",
    "Online",
    "Actually three smaller websites in a trench coat",
    "No, we don't have a Hugo",
    "At World's End",
    "Currently Hosting 128471 Stories",
    "Founded on Spite",
    "Every time you complain about the slogan, we add another one!",
    "The Future of Fiction’s Past, Today!",
    "Origins, pt. 2—Alpha 0.2.0"
];