export { HomeComponent } from './home.component';
export { LatestComponent } from './latest/latest.component';
export { WatchingComponent } from './watching/watching.component';
export { CollectionsComponent } from './collections/collections.component';
export { HistoryComponent } from './history/history.component';
export { BlogsComponent } from './blogs/blogs.component';
export { WorksComponent } from './works/works.component';
export { InboxComponent } from './inbox/inbox.component';
export { SettingsComponent } from './settings/settings.component';
