export enum Genres {
    ActionAdventure = 'Action/Adventure',
    Drama = 'Drama',
    SliceOfLife = 'Slice of Life',
    Comedy = 'Comedy',
    Romance = 'Romance',
    ScienceFiction = 'Science Fiction',
    Fantasy = 'Fantasy',
    Horror = 'Horror',
    Thriller = 'Thriller',
    Mystery = 'Mystery',
    Essay = 'Essay',
    Journalism = 'Journalism',
    Biography = 'Biography', 
    Memoir = 'Memoir',
    Limerick = 'Limerick',
    Haiku = 'Haiku',
    Sonnet = 'Sonnet',
    Ballad = 'Ballad',
    Ode = 'Ode',
    FreeVerse = 'Free Verse',
    FixedVerse = 'Fixed Verse'
}
