export const slogans: string[] = [
    'For the stories waiting to be told',
    'Tastes Like Fine Wine',
    'aaaaaaaaaaaaaaaaa',
    'Thanks for the cookies!',
    'Sample Text',
    'Not Secretly a Subsidiary of the Canadian Government',
    'Not Batman. Seriously.',
    'This is the dev team. We’re locked in a basement. Send help.',
    'Writer? I hardly even know ‘er!',
    'For All Your Times New Roman-Free Fanfiction Needs',
    'All-Natural, Ethically Sourced, Free Range, and Asbestos-Free',
    'You Probably Learned About This Site From Discord',
    'The archive we didn’t ask for, but the one we deserved',
    'Originally part of a larger publication',
    'We may or may not be Futurama fans',
    'Acquitted by a Jury of Our Peers',
    `Crime-free since ${new Date().toLocaleString()}`,
    'May contain nuts',
    'On-Brand',
    `Don't think about it too hard`,
    'Find the Comic Sans and Win a Prize',
    'There is no dress code',
    'Our slogan changes every 5 seconds',
    'Online',
    'Actually three smaller websites in a trench coat',
    'No, we don\'t have a Hugo',
    'At World\'s End',
    'Founded on Spite',
    'Every time you complain about the slogan, we add another one!',
    'The Future of Fiction’s Past, Today!',
    'Onprint. Offprint. Onprint. Offprint.',
    'You\'re today\'s 69th visitor! Nice',
    'Fanfics will continue until morale improves',
    'Hire a wizard!',
    'Here be dragons',
    'Watch out for stairs!',
    'We warned you about the stairs, bro',
    'Miniature technicolor equines!',
    'I got 99 problems but offprint ain\'t one',
    'Word salad!',
    'Dev team needs coffee',
    'The cake is a lie',
    'Love & tolerate',
    'Friendship is Magic!',
    'Free hugs!',
    'Deluxe hugs $2',
    'Do the thing, win the points',
    'Publishing since 2020',
    'May cause side-effects',
    'The beans are under the milk',
    'Who\'s this douchebag?',
    'Call your mother!',
    'Save a tree, eat a beaver',
    '*lick*',
    'Don\'t eat the delicious ponies',
    'We met in a tavern!',
    'Did you see that terrible display last night?',
    'Have you tried turning it off and then on again?',
    'Don\'t talk about Fight Club',
    'Do not talk about Fight Club',
    'Eat your veggies! Or don\'t, I\'m not your mother',
    'When in doubt, hug it out',
    'Do not feed after midnight',
    '<This space intentionally left blank>',
    'There once was a man from Nantucket...',
    'Quoth the lemming: "Geronimo!"',
    'For honor and glory and stuff',
    'Beware of rabbit',
    'Make a saving throw!',
    'I cast Magic Missile at the darkness',
    '( . Y . )',
    'Roxylicious!',
    'Figments is very moist',
    'Roxy found the slogan file!',
];
