name: Build & Test API

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'turbo.json'
      - 'package.json'
      - 'apps/api/**'
      - '.github/workflows/build-and-test-api.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0

      - name: Install global dependencies
        run: yarn global add @nestjs/cli typescript

      - name: Install local dependencies
        run: yarn install

      - name: Build API
        run: yarn workspace @dragonfish/api build
