name: Deploy to Production

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    workflow_dispatch:
        inputs:
            version:
                description: Bump version
                default: 0.0.1
                required: true
            git-ref:
                description: Git Ref (Optional)
                required: false
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    bump-version:
        name: Bump Site Version
        runs-on: ubuntu-latest
        steps:
            - name: Get the repo
              uses: actions/checkout@v2
              
            - name: Bump site version
              run: git tag ${{ github.event.inputs.version }}
    
    deploy:
        name: Deploy to Production
        runs-on: ubuntu-latest
        steps:
            - name: Close Repository (Latest)
              uses: actions/checkout@v2
              if: github.event.inputs.git-ref == ''
            
            - name: Clone Repository (Custom Ref)
              uses: actions/checkout@v2
              if: github.event.inputs.git-ref != ''
              with:
                ref: ${{ github.event.inputs.git-ref }}
            
            - name: Trigger Render Deployment
              uses: joelwmale/webhook-action@master
              with:
                url: ${{ secrets.RENDER_PROD_ENV_DEPLOY_HOOK }}
